config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :users
  get 'login/index'
  post 'login/sign_in'
  get 'login/sign_out'
  # get 'users/new'
  # post 'users/create'
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    
    @EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
    validates :firstname, presence: true
    validates :surname, presence: true
    validates :email, presence: true, :format => @EMAIL_REGEX
    validates :password, presence: true
    validates_confirmation_of :password, message: "must be the same"
    validates_length_of :password, in: 6..20, message: "must be strong (from 6 to 20 digits)"
    validates_uniqueness_of :email, message: "must be unique"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include LoginHelper
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def index
    end

    def sign_in
        @user = User.find_by(email: params[:session][:email].downcase)
        if(@user && @user.password == params[:session][:password])
            log_in @user
            redirect_to users_path
        else
            flash[:danger] = 'Invalid email/password combination'
            redirect_to login_index_path
        end
    end
    
    def sign_out
        log_out
        redirect_to login_index_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user
    def index
        @users = User.select(:id, :firstname, :surname, :email, :password)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to users_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if @user.update(user_params)
            redirect_to users_path
        else
            render 'edit'
        end
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
    
        redirect_to users_path
    end

    private
        def user_params
            params.require(:user).permit(:firstname, :surname, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
  
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def logged_in_user
        unless logged_in?
           flash[:danger] = "Please log in."
           redirect_to login_index_path
        end
    end

    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">User Administration</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to('Sign Out', login_sign_out_path)%></li>
          <% else %>
            <li><%= link_to('Sign In', login_index_path)%></li>
          <% end %>
        </ul>
      </div>
    </nav>
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
<div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <div id="new">
                    <h1>Sign in</h1>
                    
                    
                <%= form_for(:session, url: login_sign_in_path) do |f| %>
                <div class="form-group">
                    <%= f.label(:email, "Login:") %>
                    <%= f.email_field(:email, class: "form-control") %>
                </div>
                <div class="form-group">
                    <%= f.label(:password, "Password:") %>
                    <%= f.password_field(:password, class: "form-control") %>
                </div>
                <div class="form-group">
                    <%= f.submit("Sign In", class: "btn btn-primary")%>
                <% end %>
                </div>
            </div>
        </div>
    </div>
    

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@user.errors.count, "error") %> prohibited
    this article from being saved:
  </h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_with model: @user, local: true do |u| %>
<div class="form-group">
    <%= u.label(:firstname, "First Name") %>
    <%= u.text_field(:firstname, class: "form-control") %>
</div>
<div class="form-group">
    <%= u.label(:surname, "Surname") %>
    <%= u.text_field(:surname, class: "form-control") %>
</div>
<div class="form-group">
    <%= u.label(:email, "E-mail") %>
    <%= u.text_field(:email, class: "form-control") %>
</div>
<div class="form-group">
    <%= u.label(:password, "Password") %>
    <%= u.password_field(:password, class: "form-control") %>
</div>
<div class="form-group">
    <%= u.label(:password_confirmation, "Password confirmation") %>
    <%= u.password_field(:password_confirmation, class: "form-control") %>
</div>
<%= u.submit "Send", class: "btn btn-primary"%>
<%= link_to('Back', users_index_path, class: "btn btn-primary") %>
<% end %> 

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <div id="new">
                <h1>Edit user: <%= @user.firstname %></h1>
                
            <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <div id="list">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>List of users</h1>
                            <%= link_to("Add user", new_user_path, class: "btn btn-primary float-right")%>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-striped">
                                <tr>
                                    <th>First name</th>
                                    <th>Surname</th>
                                    <th>E-mail</th>
                                    <th>Password</th>
                                    <th>Actions</th>
                                </tr>
                                <% @users.each do |user| %>
                                <tr>
                                    <td><%=user.firstname%></td>
                                    <td><%=user.surname%></td>
                                    <td><%=user.email%></td>
                                    <td><%=user.password%></td>
                                    <td>
                                        <%= link_to('Edit', edit_user_path(user), class: "btn btn-primary") %>
                                        <%= link_to('Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger") %>
                                    </td>
                                </tr>
                                <% end%>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <div id="new">
                <h1>New user</h1>
                
            <%= render 'form' %>
            </div>
        </div>
    </div>
</div>